---
title: "Catalonia data"
author: "www.databrew.cc"
date: "May 17, 2018"
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(comment = NA, echo = FALSE, warning = FALSE, message = FALSE, error = FALSE, fig.align = 'center', fig.height = 4, fig.width = 7, fig.path = "figures/")
options(xtable.comment = FALSE)
library(databrew)

# Define colors
make_colors <- function(n, categorical = TRUE){
  if(categorical){
    cols <- c('#ffd700' ,'#f69500', '#f29672', '#d66857', '#9c4040', '#8d65a0', '#5e498d', '#328cc1', '#076d86', '#5cd29a', '#206535', '#5c8939', '#d0d3c5', '#b0acac', '#3e3e3e')
  } else {
    cols <- c("#16394d","#3b4e64","#02507d","#2974a0","#328cc1","#59acd7","#76b7dc","#b9dff9","#d1eaf7","#dde9ef")
  }
  out <- colorRampPalette(colors = cols)(n)
  return(out)
}

# Define function for getting weighted percentage 
make_data <- function(data = df,
                      y = 'independence',
                      x = 'birth'){
  
  data <- data %>%
    dplyr::select_('weight', x, y)
  out <- data %>%
    group_by_(x,y) %>%
    summarise(people = sum(weight)) %>%
    ungroup %>%
    group_by_(x) %>%
    mutate(p = people / sum(people) * 100) %>%
    ungroup 
  return(out)
}
plot_data <- function(made_data,
                      legend_title = NULL,
                      label_p = FALSE,
                      label_size = NULL,
                      cols = NULL){
  nd <- names(made_data)
  names(made_data) <- c('x', 'y', 'n', 'p')
  if(is.null(cols)){
    cols <- make_colors(length(unique(made_data$y)))
  }
  if(is.null(label_size)){
    label_size = 3
  }
  g <- ggplot(data = made_data %>% filter(!is.na(x)),
         aes(x = x,
             y = p,
             group = y,
             fill = y)) +
    geom_bar(stat = 'identity',
             position = 'dodge') +
    labs(x = Hmisc::capitalize(nd[1]),
         y = 'Percent') +
    theme_databrew()
  if(is.null(legend_title)){
    legend_title <- nd[2]
  }
  if(label_p){
    g <- g + 
      geom_text(data = made_data, 
             aes(
               y = p + (max(p) * 0.1),
             label = round(p, digits = 1)),
             position = position_dodge(width = 1),
             alpha = 0.7,
             size = label_size)
  }
  g <- g +
      scale_fill_manual(name = legend_title,
                      values = cols )
    
  return(g)
}

source('prepare_data.R')
```

```{r}
library(raster)
library(sp)
esp <- raster::getData(name = 'GADM',
                       level = 4,
                       country = 'ESP')
cat <- esp[esp@data$NAME_1 == 'Cataluña',]
cat_fortified <- broom::tidy(cat, id = 'region')


colors <- make_colors(length(unique(cat_fortified$group)), categorical = FALSE)
colors <- sample(colors, length(colors))
ggplot(data = cat_fortified,
       aes(x = long,
           y = lat,
           group = group)) + #,
           # group = group,
           # fill = group)) +
  geom_polygon(alpha = 0.9,
       fill = 'yellow',
       color = 'blue',
       size = 0.1) + 
  theme_databrew() +
  ggthemes::theme_map() 
  # scale_fill_manual(name = '',
  #                   values = colors) +
  #   theme(legend.position = 'none') 
```

# Independence views

```{r}
pd <- df %>%
  group_by(independence, independence) %>%
  summarise(n = sum(weight)) %>%
  ungroup %>%
  mutate(p = n / sum(n) * 100)
ggplot(data = pd,
       aes(x = independence,
           y = p)) +
  geom_bar(stat = 'identity',
           fill = make_colors(3)[1],
           color = make_colors(3)[2]) +
  geom_text(aes(label = paste0(round(p, digits = 2), '%'),
                y = p + 3),
             size = 6) +
  theme_databrew() +
  labs(x = '',
       y = 'Percent',
       title = 'Do you want Catalonia to be an independent state?') +
  theme(axis.text.x = element_text(size = 15))
```

## By birth place

```{r}
pd <- make_data(data = df,
                      x = 'birth',
                      y = 'independence')
plot_data(made_data = pd,
          legend_title = '',
          label_p = TRUE) +
  labs(title = 'Do you want Catalonia to be an independent state?',
       x = 'Place of birth')
```

## By mother's birth place

```{r}
pd <- make_data(data = df,
                      x = 'birth_mother',
                      y = 'independence')
plot_data(made_data = pd,
          legend_title = '',
          label_p = TRUE) +
  labs(title = 'Do you want Catalonia to be an independent state?',
       x = 'Mother\'s place of birth')
```

## By father's birth place

```{r}
pd <- make_data(data = df,
                      x = 'birth_father',
                      y = 'independence')
plot_data(made_data = pd,
          legend_title = '',
          label_p = TRUE) +
  labs(title = 'Do you want Catalonia to be an independent state?',
       x = 'Father\'s place of birth')
```

## By both parents' place of birth

```{r}
pd <- make_data(data = df,
                      x = 'birth_parents',
                      y = 'independence')
plot_data(made_data = pd,
          legend_title = '',
          label_p = TRUE) +
  labs(title = 'Do you want Catalonia to be an independent state?',
       x = 'Parents\' place of birth')
```


## By grandparents' place of birth

```{r}
pd <- make_data(data = df,
                      x = 'birth_grandparents',
                      y = 'independence')
plot_data(made_data = pd,
          legend_title = '',
          label_p = TRUE) +
  labs(title = 'Do you want Catalonia to be an independent state?',
       x = 'Number of grandparents born in Catalonia')
```

## By sex

```{r}
pd <- make_data(data = df,
                      x = 'sex',
                      y = 'independence')
plot_data(made_data = pd,
          legend_title = '',
          label_p = TRUE) +
  labs(title = 'Do you want Catalonia to be an independent state?',
       x = 'Sex')
```

## By education

```{r}
pd <- make_data(data = df,
                      x = 'education',
                      y = 'independence')
plot_data(made_data = pd,
          legend_title = '',
          label_p = TRUE) +
  labs(title = 'Do you want Catalonia to be an independent state?',
       x = 'Education') +
  theme(axis.text.x = element_text(angle = 90))
```

```{r}
x <- df %>%
  group_by(education) %>%
  summarise(p_ind = sum(weight[independence == 'Yes']) / sum(weight[independence %in% c('Yes', 'No')]) * 100) %>%
  ungroup %>% 
  filter(!is.na(education))
ggplot(data = x,
       aes(x = education,
           y = p_ind)) +
  geom_area(fill = 'yellow',
            alpha = 0.7,
            group = 1) +
  geom_point(color = 'blue',
             alpha = 0.7) +
  geom_line(group = 1,
            color = 'blue',
            alpha = 0.7) +
  theme_databrew() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = 'Education',
       y = '% yes',
       title = 'Do you want Catalonia to be an independent state?',
       subtitle = '(Excluding those who did not respond or did not know)') +
  ylim(0, 100) +
  geom_hline(yintercept = 50, lty = 2, alpha = 0.6)
```

## By age

```{r}
ggplot(data = df %>% filter(independence %in% c('Yes', 'No')),
       aes(x = age,
           group = independence,
           fill = independence)) +
  geom_density(alpha= 0.8) +
  scale_fill_manual(name = '',
                    values = make_colors(3)[1:2]) +
  theme_databrew() +
  labs(title = 'Do you want Catalonia to be an independent state?',
       x = 'Age',
       y = 'Density')
```

```{r}
x <- df %>% mutate(agex = round(age, digits = -1)) %>%
  filter(agex < 100) %>%
  group_by(agex) %>%
  mutate(agey = paste0(min(age), '-', max(age))) %>%
  ungroup %>%
  mutate(age = agey) %>%
  mutate(age = factor(age))
pd <- make_data(data = x,
                      x = 'age',
                      y = 'independence')
plot_data(made_data = pd,
          legend_title = '',
          label_p = TRUE,
          label_size = 3) +
  labs(title = 'Do you want Catalonia to be an independent state?',
       x = 'Age')
```

## By income

```{r}
x <- df %>%
  group_by(income) %>%
  summarise(p_ind = sum(weight[independence == 'Yes']) / sum(weight[independence %in% c('Yes', 'No')]) * 100) %>%
  ungroup %>% 
  filter(! income %in% c('0'),
         !is.na(income))
ggplot(data = x,
       aes(x = income,
           y = p_ind)) +
  geom_area(fill = 'yellow',
            alpha = 0.7,
            group = 1) +
  geom_point(color = 'blue',
             alpha = 0.7) +
  geom_line(group = 1,
            color = 'blue',
            alpha = 0.7) +
  theme_databrew() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = 'Monthly income (euros)',
       y = '% yes',
       title = 'Do you want Catalonia to be an independent state?',
       subtitle = '(Excluding those who did not respond or did not know)') +
  ylim(0, 100) +
  geom_hline(yintercept = 50, lty = 2, alpha = 0.6)
```

## By language

### Main language

```{r}
pd <- make_data(data = df,
                      x = 'language',
                      y = 'independence')
plot_data(made_data = pd,
          legend_title = '',
          label_p = TRUE) +
  labs(title = 'Do you want Catalonia to be an independent state?',
       x = 'Language',
       subtitle = 'Which language do you consider to be your own?') +
  theme(axis.text.x = element_text(angle = 90))
```

### Habitual language

```{r}
pd <- make_data(data = df,
                      x = 'language_habitual',
                      y = 'independence')
plot_data(made_data = pd,
          legend_title = '',
          label_p = TRUE) +
  labs(title = 'Do you want Catalonia to be an independent state?',
       x = 'Language',
       subtitle = 'Which language do you speak most often?') +
  theme(axis.text.x = element_text(angle = 90))
```


### First language

```{r}
pd <- make_data(data = df,
                      x = 'language_first',
                      y = 'independence')
plot_data(made_data = pd,
          legend_title = '',
          label_p = TRUE) +
  labs(title = 'Do you want Catalonia to be an independent state?',
       x = 'Language',
       subtitle = 'Which language did you speak first?') +
  theme(axis.text.x = element_text(angle = 90))
```

## By religion

```{r}
pd <- make_data(data = df,
                      x = 'religion',
                      y = 'independence')
plot_data(made_data = pd,
          legend_title = '',
          label_p = TRUE) +
  labs(title = 'Do you want Catalonia to be an independent state?',
       x = 'Religion',
       subtitle = 'Do you attend religious ceremonies at least yearly?') +
  theme(axis.text.x = element_text(angle = 90))
```

## By feeling


```{r}
x <- df %>%
  group_by(feel) %>%
  summarise(p_ind = sum(weight[independence == 'Yes']) / sum(weight[independence %in% c('Yes', 'No')]) * 100) %>%
  ungroup %>%
  filter(!is.na(feel))
ggplot(data = x,
       aes(x = feel,
           y = p_ind)) +
  geom_area(fill = 'yellow',
            alpha = 0.7,
            group = 1) +
  geom_point(color = 'blue',
             alpha = 0.7) +
  geom_line(group = 1,
            color = 'blue',
            alpha = 0.7) +
  theme_databrew() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = 'With which phrase do you self-identify',
       y = '% yes',
       title = 'Do you want Catalonia to be an independent state?',
       subtitle = '(Excluding those who did not respond or did not know)') +
  ylim(0, 100) +
  geom_hline(yintercept = 50, lty = 2, alpha = 0.6)
```

## Party and language
```{r}
pd <- df %>%
  group_by(language, party, pro_ind, referendum) %>%
  summarise(n = sum(weight)) %>%
  ungroup %>%
  filter(!is.na(referendum)) %>%
  group_by(party) %>%
  mutate(p = n / sum(n) * 100) %>%
  ungroup %>%
  arrange(referendum) %>%
  # mutate(party = factor(party,
  #                       levels = unique(party))) %>%
    filter(language != 'Other')
g1 <- ggplot(data = pd %>% filter(pro_ind == 'Yes'),
       aes(x = party,
           y = p,
           fill = language,
           group = language)) +
  geom_bar(stat = 'identity',
           position = 'dodge',
           width = 1) +
    theme_databrew() +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_fill_manual(name = '',
                    values = make_colors(length(unique(pd$language)))) +
  geom_text(aes(label = paste0(round(p, digits = 0), '%'),
                y = p + 5),
             size = 3,
            alpha = 0.7,
            position = position_dodge(width = 1)) +
   labs(subtitle = 'Pro-independence parties',
       x = '',
       y = 'Percent',
       title = '') +
  ylim(0,100)
g2 <- ggplot(data = pd %>% filter(pro_ind == 'No'),
       aes(x = party,
           y = p,
           fill = language,
           group = language)) +
  geom_bar(stat = 'identity',
           position = 'dodge',
           width = 1) +
    theme_databrew() +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_fill_manual(name = '',
                    values = make_colors(length(unique(pd$language)))) +
  geom_text(aes(label = paste0(round(p, digits = 0), '%'),
                y = p + 5),
             size = 3,
            alpha = 0.7,
            position = position_dodge(width = 1)) +
   labs(subtitle = 'Pro-union parties',
       x = '',
       y = 'Percent',
       title = '') +
  ylim(0,100)
Rmisc::multiplot(g1, g2, cols = 2)
```

## View of Europe

```{r}
ggplot(data = df %>% filter(independence %in% c('Yes', 'No'),
                            view_europe <= 10),
       aes(x = independence,
           y = view_europe,
           group = independence,
           color = independence)) +
  geom_jitter() +
  geom_violin(alpha = 0.8) +
  scale_color_manual('Pro-independence',
                     values = make_colors(3)[1:2]) +
  theme_databrew() +
  labs(title = 'Do you want Catalonia to be an independent state?',
       x = 'Age',
       y = 'Opinion of Europe')
```

```{r, echo = TRUE}
# Europe
df %>% filter(independence %in% c('Yes', 'No'),
                            view_europe <= 10) %>%
  group_by(independence) %>%
  summarise(avg = mean(view_europe),
            med = median(view_europe))
  
# Church
df %>% filter(independence %in% c('Yes', 'No'),
                            view_church <= 10) %>%
  group_by(independence) %>%
  summarise(avg = mean(view_church),
            med = median(view_church))

# Monarchy
df %>% filter(independence %in% c('Yes', 'No'),
                            view_monarchy <= 10) %>%
  group_by(independence) %>%
  summarise(avg = mean(view_monarchy),
            med = median(view_monarchy))

# Monarchy
df %>% filter(independence %in% c('Yes', 'No'),
                            view_military <= 10) %>%
  group_by(independence) %>%
  summarise(avg = mean(view_military),
            med = median(view_military))

# Spanish govt
df %>% filter(independence %in% c('Yes', 'No'),
                            view_spain_govt <= 10) %>%
  group_by(independence) %>%
  summarise(avg = mean(view_spain_govt),
            med = median(view_spain_govt))
```

```{r}
x <-df[,grepl('view|independence', names(df))]
x <- gather(x, key, value, view_europe:view_military)
x <- x %>%
  filter(value <= 10) %>%
  mutate(key = gsub('view_', '', key)) %>%
  group_by(independence, key) %>%
  summarise(value = mean(value)) %>%
  ungroup %>%
  filter(independence %in% c('Yes', 'No'))
view_dict <- data_frame(
  key = c('church', 'europe', 'military', 'monarchy', 'spain_govt'),
  new_key = c('Church', 'European Union', 'Spanish Military', 'Spanish Monarchy', 'Sp. Government')
)
x <- x %>% left_join(view_dict)
ggplot(data = x %>% filter(!key %in% c('europe', 'spain_govt', 'church')),
       aes(x = independence,
           y = value,
           fill = independence)) +
  geom_bar(stat = 'identity',
           position = position_dodge(width = 1)) +
  facet_wrap(~new_key) +
  theme_databrew() +
  scale_fill_manual(name = 'Pro independence',
                    values = make_colors(3)[1:2]) +
  theme(legend.position = 'none') +
  labs(x = 'Pro-independence?',
       y = 'Favorability (0-10)')
```
